"""
Exposes the repo's data_schema.md (generated by generate_data_schema.py) so
data_agent's system prompt and get_schema tool describe the real, current
columns instead of a hand-maintained copy that can drift out of sync.
"""

from __future__ import annotations

from functools import lru_cache
from pathlib import Path

# ecom-multi-agent/data_agent/tools/schema.py -> repo_root/data_schema.md
SCHEMA_MD_PATH = Path(__file__).resolve().parents[3] / "data_schema.md"

# Join keys as documented in README.md section 2 — the ones data_agent tools
# actually implement.
JOIN_KEYS = [
    "orders.customer_id -> customers.customer_id",
    "orders.order_id -> order_items.order_id",
    "orders.order_id -> order_payments.order_id",
    "orders.order_id -> order_reviews.order_id",
    "order_items.product_id -> products.product_id",
    "order_items.seller_id -> sellers.seller_id",
    "products.product_category_name -> product_category_name_translation.product_category_name",
    "*.zip_code_prefix -> geolocation.geolocation_zip_code_prefix (many-to-many, not a row key)",
]


@lru_cache(maxsize=1)
def get_schema_markdown() -> str:
    """Full data_schema.md contents (table overview + ERD + per-column detail)."""
    if not SCHEMA_MD_PATH.exists():
        return (
            "data_schema.md not found. Run `python generate_data_schema.py` "
            "from the repo root to generate it."
        )
    return SCHEMA_MD_PATH.read_text(encoding="utf-8")


@lru_cache(maxsize=1)
def get_schema_overview() -> str:
    """Just the table-level overview + join keys, for use inside prompts."""
    md = get_schema_markdown()
    marker = "## Entity-Relationship Diagram"
    overview = md.split(marker, 1)[0] if marker in md else md
    joins = "\n".join(f"- {j}" for j in JOIN_KEYS)
    return f"{overview}\n## Join Keys\n\n{joins}\n"
